# do not create a queue: section for your test environment
test:
  adapter: postgresql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: canvas
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_development
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: localhost
  username: postgres
  password: sitiofundamentos2018
  timeout: 5000
